package inventorysystem.dao.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Wed Feb 24 17:48:40 CST 2010]
  *
  */
public class ORF_SupplyMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "inventorysystem.dao.map.ORF_SupplyMapBuilder";


    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("inventorysystemdb");

        dbMap.addTable("orf_supply");
        TableMap tMap = dbMap.getTable("orf_supply");

        tMap.setPrimaryKeyMethod(TableMap.NATIVE);


              tMap.addForeignPrimaryKey(
                "orf_supply.ORF_ID", new Integer(0) , "orf" ,
                "orf_id");
                    tMap.addForeignPrimaryKey(
                "orf_supply.USER_ID", new Integer(0) , "user" ,
                "user_id");
                    tMap.addColumn("orf_supply.SUPPLY_TYPE", new String());
                    tMap.addColumn("orf_supply.SUPPLY_NAME", new String());
                    tMap.addColumn("orf_supply.QUANTITY", new String());
                    tMap.addColumn("orf_supply.PRICE", new String());
          }
}
