
package inventorysystem.dao;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Feb 12 16:07:54 SGT 2010]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class ORF
    extends inventorysystem.dao.BaseORF
    implements Persistent
{
       public String returnPendingORF(){
        int orfID = this.getORF_ID();
        String issueDate = this.getIssue_Date();
        int user = this.getUser_ID();
        String username = UserPeer.retrieveUserByID(user);
        String ORF = orfID+":"+issueDate+":"+username;
        return(ORF);
    }
}
