
package inventorysystem.dao;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Feb 12 16:07:54 SGT 2010]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class ORF_Supply
    extends inventorysystem.dao.BaseORF_Supply
    implements Persistent
{
}
