package inventorysystem.dao;

import java.util.ArrayList;
import java.util.List;
import org.apache.torque.util.Criteria;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Feb 12 16:07:54 SGT 2010]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class ORFPeer
    extends inventorysystem.dao.BaseORFPeer
{
     public static boolean addORF(int userID,String ts){

        Criteria criteria = new Criteria();
        criteria.add(ORFPeer.STATUS, false);
        criteria.add(ORFPeer.USER_ID,userID);
        criteria.add(ORFPeer.ISSUE_DATE, ts);

        try{
            ORFPeer.doInsert(criteria);
            return true;
        }catch(Exception e){
            e.printStackTrace();
            return false;
        }
    }

     public static ORF getORF(String ts, int userID){
        Criteria criteria = new Criteria();
        criteria.add(ORFPeer.USER_ID, userID);
        criteria.add(ORFPeer.ISSUE_DATE, ts);
        try{
            return (ORF)ORFPeer.doSelect(criteria).get(0);
        }catch(Exception e){
            e.printStackTrace();
            return null;
        }
    }
         public static List<ORF> retrieveInactiveORF(){
        Criteria criteria = new Criteria();
        criteria.add(STATUS, 0);
        try{
            return (List<ORF>)ORFPeer.doSelect(criteria);
        }catch(Exception e){
            e.printStackTrace();
            return new ArrayList<ORF>();
        }
    }

    public static boolean setORFAcknowledged(int orf_ID){
        Criteria selectCriteria = new Criteria();
        selectCriteria.add(ORFPeer.ORF_ID, orf_ID);

        Criteria criteria = new Criteria();
        criteria.add(ORF_SupplyPeer.STATUS, 1);

        try{
            ORFPeer.doUpdate(selectCriteria, criteria);
            return true;
        }catch(Exception e){
            e.printStackTrace();
            return false;
        }
    }

}
