package inventorysystem.dao;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Feb 12 16:07:54 SGT 2010]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */

import org.apache.torque.util.Criteria;
import java.util.List;
import java.util.ArrayList;

public class ORF_SupplyPeer
    extends inventorysystem.dao.BaseORF_SupplyPeer
{
        public static boolean addORFSupply(int orf_id,int user_id, String supplyType, String supplyName, String supplyQuantity, String supplyPrice){

        Criteria criteria = new Criteria();
        criteria.add(ORF_SupplyPeer.ORF_ID, orf_id);
        criteria.add(ORF_SupplyPeer.USER_ID, user_id);
        criteria.add(ORF_SupplyPeer.SUPPLY_NAME, supplyName);
        criteria.add(ORF_SupplyPeer.SUPPLY_TYPE, supplyType);
        criteria.add(ORF_SupplyPeer.QUANTITY, supplyQuantity);
        criteria.add(ORF_SupplyPeer.PRICE, supplyPrice);

        try{
            ORF_SupplyPeer.doInsert(criteria);
            return true;
        }catch(Exception e){
            e.printStackTrace();
            return false;
        }
    }
      public static List<ORF_Supply> retrieveORFSupply(int orf_ID){
        Criteria criteria = new Criteria();
        criteria.add(ORF_SupplyPeer.ORF_ID, orf_ID);
        try{
            return (List<ORF_Supply>) ORF_SupplyPeer.doSelect(criteria);
        }catch(Exception e){
            e.printStackTrace();
            return new ArrayList<ORF_Supply>();
        }
      }
      public static List<ORF_Supply> retrieveUnacknowledgedORFSupply(int orf_ID){
         Criteria criteria = new Criteria();
         criteria.add(ORF_SupplyPeer.ORF_ID, orf_ID);
         criteria.add(ORF_SupplyPeer.STATUS, 0);
         try{
             return (List<ORF_Supply>) ORF_SupplyPeer.doSelect(criteria);
         }
         catch(Exception e){
             e.printStackTrace();
            return new ArrayList<ORF_Supply>();
         }
      }

      public static boolean setORFSupplyAcknowledged(int orfSupply_ID){
        Criteria selectCriteria = new Criteria();
        selectCriteria.add(ORF_SupplyPeer.ORF_SUPPLYID,orfSupply_ID);

        Criteria criteria = new Criteria();
        criteria.add(ORF_SupplyPeer.STATUS, 1);

        try{
            ORF_SupplyPeer.doUpdate(selectCriteria, criteria);
            return true;
        }catch(Exception e){
            e.printStackTrace();
            return false;
        }
    }



}
