package inventorysystem.dao;

import java.util.ArrayList;
import java.util.List;
import org.apache.torque.util.Criteria;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Mar 15 20:34:49 SGT 2010]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class Supply_PhyChemPeer
    extends inventorysystem.dao.BaseSupply_PhyChemPeer
{
   public static List<Supply_PhyChem> retrieveAllSupplies(){
        Criteria criteria = new Criteria();
        try{
            return (List<Supply_PhyChem>)Supply_PhyChemPeer.doSelect(criteria);
        }catch(Exception e){
            e.printStackTrace();
            return new ArrayList<Supply_PhyChem>();
        }
    }

    public static Supply_PhyChem retrieveSupply(String supplyname){
        Criteria criteria = new Criteria();
        criteria.add(Supply_PhyChemPeer.NAME, supplyname);
        try{
            return (Supply_PhyChem)Supply_PhyChemPeer.doSelect(criteria).get(0);
        }catch(Exception e){
            e.printStackTrace();
            return null;
        }
    }

    public static List<Supply_PhyChem> retrieveSuppliesByType(String supplyType){
        Criteria criteria = new Criteria();
        criteria.add(Supply_PhyChemPeer.TYPE, supplyType);
        try{
            return (List<Supply_PhyChem>)Supply_PhyChemPeer.doSelect(criteria);
        }catch(Exception e){
            e.printStackTrace();
            return new ArrayList<Supply_PhyChem>();
        }
    }

    public static boolean editSupply(String supplyName, String supplyType, String supplyQuantity, String amount, String unit){

        Criteria selectCriteria = new Criteria();
        selectCriteria.add(Supply_PhyChemPeer.NAME, supplyName);

        Criteria criteria = new Criteria();
        criteria.add(Supply_PhyChemPeer.NAME, supplyName);
        criteria.add(Supply_PhyChemPeer.TYPE, supplyType);
        criteria.add(Supply_PhyChemPeer.QUANTITY, Integer.parseInt(supplyQuantity));


        if(amount.isEmpty()){
            criteria.add(Supply_PhyChemPeer.AMOUNT, null);
        }else{
            criteria.add(Supply_PhyChemPeer.AMOUNT, Integer.parseInt(amount));
        }
        if(unit.equals("novalue")){
            criteria.add(Supply_PhyChemPeer.UNIT, null);
        }else{
            criteria.add(Supply_PhyChemPeer.UNIT, unit);
        }

        try{
            Supply_PhyChemPeer.doUpdate(selectCriteria, criteria);
            return true;
        }catch(Exception e){
            e.printStackTrace();
            return false;
        }
    }

    public static boolean addSupply(String supplyName, String supplyType, String supplyQuantity, String amount, String unit){

        Criteria criteria = new Criteria();
        criteria.add(Supply_PhyChemPeer.NAME, supplyName);
        criteria.add(Supply_PhyChemPeer.TYPE, supplyType);
        criteria.add(Supply_PhyChemPeer.QUANTITY, Integer.parseInt(supplyQuantity));
     

        if(amount.isEmpty()){
            criteria.add(Supply_PhyChemPeer.AMOUNT, null);
        }else{
            criteria.add(Supply_PhyChemPeer.AMOUNT, Integer.parseInt(amount));
        }
        if(unit.equals("novalue")){
            criteria.add(Supply_PhyChemPeer.UNIT, null);
        }else{
            criteria.add(Supply_PhyChemPeer.UNIT, unit);
        }

        try{
            Supply_PhyChemPeer.doInsert(criteria);
            return true;
        }catch(Exception e){
            e.printStackTrace();
            return false;
        }
    }

    public static boolean deleteSupply(String supplyName){
        Criteria criteria = new Criteria();
        criteria.add(Supply_PhyChemPeer.NAME, supplyName);
        try{
            Supply_PhyChemPeer.doDelete(criteria);
            return true;
        }catch(Exception e){
            e.printStackTrace();
            return false;
        }

     }
}
