package inventorysystem.dao;

import java.util.ArrayList;
import java.util.List;
import org.apache.torque.util.Criteria;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Mar 15 20:34:49 SGT 2010]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class Supply_BioChemPeer
    extends inventorysystem.dao.BaseSupply_BioChemPeer
{ 
    public static List<Supply_BioChem> retrieveAllSupplies(){
        Criteria criteria = new Criteria();
        try{
            return (List<Supply_BioChem>)Supply_BioChemPeer.doSelect(criteria);
        }catch(Exception e){
            e.printStackTrace();
            return new ArrayList<Supply_BioChem>();
        }
    }

    public static Supply_BioChem retrieveSupply(String supplyname){
        Criteria criteria = new Criteria();
        criteria.add(Supply_BioChemPeer.NAME, supplyname);
        try{
            return (Supply_BioChem)Supply_BioChemPeer.doSelect(criteria).get(0);
        }catch(Exception e){
            e.printStackTrace();
            return null;
        }
    }

    public static List<Supply_BioChem> retrieveSuppliesByType(String supplyType){
        Criteria criteria = new Criteria();
        criteria.add(Supply_BioChemPeer.TYPE, supplyType);
        try{
            return (List<Supply_BioChem>)Supply_BioChemPeer.doSelect(criteria);
        }catch(Exception e){
            e.printStackTrace();
            return new ArrayList<Supply_BioChem>();
        }
    }

    public static boolean editSupply(String supplyName, String supplyType, String supplyQuantity, String amount, String unit){

        Criteria selectCriteria = new Criteria();
        selectCriteria.add(Supply_BioChemPeer.NAME, supplyName);

        Criteria criteria = new Criteria();
        criteria.add(Supply_BioChemPeer.NAME, supplyName);
        criteria.add(Supply_BioChemPeer.TYPE, supplyType);
        criteria.add(Supply_BioChemPeer.QUANTITY, Integer.parseInt(supplyQuantity));
      

        if(amount.isEmpty()){
            criteria.add(Supply_BioChemPeer.AMOUNT, null);
        }else{
            criteria.add(Supply_BioChemPeer.AMOUNT, Integer.parseInt(amount));
        }
        if(unit.equals("novalue")){
            criteria.add(Supply_BioChemPeer.UNIT, null);
        }else{
            criteria.add(Supply_BioChemPeer.UNIT, unit);
        }

        try{
            Supply_BioChemPeer.doUpdate(selectCriteria, criteria);
            return true;
        }catch(Exception e){
            e.printStackTrace();
            return false;
        }
    }

    public static boolean addSupply(String supplyName, String supplyType, String supplyQuantity, String amount, String unit){

        Criteria criteria = new Criteria();
        criteria.add(Supply_BioChemPeer.NAME, supplyName);
        criteria.add(Supply_BioChemPeer.TYPE, supplyType);
        criteria.add(Supply_BioChemPeer.QUANTITY, Integer.parseInt(supplyQuantity));
   

        if(amount.isEmpty()){
            criteria.add(Supply_BioChemPeer.AMOUNT, null);
        }else{
            criteria.add(Supply_BioChemPeer.AMOUNT, Integer.parseInt(amount));
        }
        if(unit.equals("novalue")){
            criteria.add(Supply_BioChemPeer.UNIT, null);
        }else{
            criteria.add(Supply_BioChemPeer.UNIT, unit);
        }

        try{
            Supply_BioChemPeer.doInsert(criteria);
            return true;
        }catch(Exception e){
            e.printStackTrace();
            return false;
        }
    }

    public static boolean deleteSupply(String supplyName){
        Criteria criteria = new Criteria();
        criteria.add(Supply_BioChemPeer.NAME, supplyName);
        try{
            Supply_BioChemPeer.doDelete(criteria);
            return true;
        }catch(Exception e){
            e.printStackTrace();
            return false;
        }

     }
}
