package inventorysystem.dao;

import java.util.ArrayList;
import java.util.List;
import org.apache.torque.util.Criteria;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sun Mar 07 22:33:27 SGT 2010]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class System_LogPeer
    extends inventorysystem.dao.BaseSystem_LogPeer
{

    public static boolean updateSystemLog(int userid, String action, String location, int prev_value, int curr_value,String notes)
    {
        java.util.Date dateNow = new java.util.Date();
        String date = dateNow.toString();

        Criteria criteria = new Criteria();
        criteria.add(System_LogPeer.USER_ID, userid);
        criteria.add(System_LogPeer.ACTION, action);
        criteria.add(System_LogPeer.LOCATION, location);
        criteria.add(System_LogPeer.PREVIOUS_VALUE, prev_value);
        criteria.add(System_LogPeer.CURRENT_VALUE, curr_value);
        criteria.add(System_LogPeer.NOTES, notes);
        criteria.add(System_LogPeer.DATE, date);

        try{
            System_LogPeer.doInsert(criteria);
            return true;
        }catch(Exception e){
            e.printStackTrace();
            return false;
        }
    }

    public static List<System_Log> retrieveSystemLog(){
        Criteria criteria = new Criteria();
        try{
            return (List<System_Log>)System_LogPeer.doSelect(criteria);
        }catch(Exception e){
            e.printStackTrace();
            return new ArrayList<System_Log>();
        }
    }
}
