
package inventorysystem.dao;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Mar 09 20:54:16 CST 2010]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class System_Log
    extends inventorysystem.dao.BaseSystem_Log
    implements Persistent
{
}
