package inventorysystem.dao;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;


/**
 * This class was autogenerated by Torque on:
 *
 * [Wed Mar 03 16:45:55 CST 2010]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Supply
 */
public abstract class BaseSupply extends BaseObject
{
    /** The Peer class */
    private static final SupplyPeer peer =
        new SupplyPeer();

        
    /** The value for the supply_ID field */
    private int supply_ID;
      
    /** The value for the type field */
    private String type;
      
    /** The value for the name field */
    private String name;
      
    /** The value for the quantity field */
    private int quantity;
      
    /** The value for the source field */
    private String source;
      
    /** The value for the location field */
    private String location;
  
    
    /**
     * Get the Supply_ID
     *
     * @return int
     */
    public int getSupply_ID()
    {
        return supply_ID;
    }

                                              
    /**
     * Set the value of Supply_ID
     *
     * @param v new value
     */
    public void setSupply_ID(int v) throws TorqueException
    {
    
                  if (this.supply_ID != v)
              {
            this.supply_ID = v;
            setModified(true);
        }
    
          
                                  
        // update associated Manages
        if (collManagess != null)
        {
            for (int i = 0; i < collManagess.size(); i++)
            {
                ((Manages) collManagess.get(i))
                    .setSupply_ID(v);
            }
        }
                      }
  
    /**
     * Get the Type
     *
     * @return String
     */
    public String getType()
    {
        return type;
    }

                        
    /**
     * Set the value of Type
     *
     * @param v new value
     */
    public void setType(String v) 
    {
    
                  if (!ObjectUtils.equals(this.type, v))
              {
            this.type = v;
            setModified(true);
        }
    
          
              }
  
    /**
     * Get the Name
     *
     * @return String
     */
    public String getName()
    {
        return name;
    }

                        
    /**
     * Set the value of Name
     *
     * @param v new value
     */
    public void setName(String v) 
    {
    
                  if (!ObjectUtils.equals(this.name, v))
              {
            this.name = v;
            setModified(true);
        }
    
          
              }
  
    /**
     * Get the Quantity
     *
     * @return int
     */
    public int getQuantity()
    {
        return quantity;
    }

                        
    /**
     * Set the value of Quantity
     *
     * @param v new value
     */
    public void setQuantity(int v) 
    {
    
                  if (this.quantity != v)
              {
            this.quantity = v;
            setModified(true);
        }
    
          
              }
  
    /**
     * Get the Source
     *
     * @return String
     */
    public String getSource()
    {
        return source;
    }

                        
    /**
     * Set the value of Source
     *
     * @param v new value
     */
    public void setSource(String v) 
    {
    
                  if (!ObjectUtils.equals(this.source, v))
              {
            this.source = v;
            setModified(true);
        }
    
          
              }
  
    /**
     * Get the Location
     *
     * @return String
     */
    public String getLocation()
    {
        return location;
    }

                        
    /**
     * Set the value of Location
     *
     * @param v new value
     */
    public void setLocation(String v) 
    {
    
                  if (!ObjectUtils.equals(this.location, v))
              {
            this.location = v;
            setModified(true);
        }
    
          
              }
  
         
                                
            
    /**
     * Collection to store aggregation of collManagess
     */
    protected List collManagess;

    /**
     * Temporary storage of collManagess to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initManagess()
    {
        if (collManagess == null)
        {
            collManagess = new ArrayList();
        }
    }

    /**
     * Method called to associate a Manages object to this object
     * through the Manages foreign key attribute
     *
     * @param l Manages
     * @throws TorqueException
     */
    public void addManages(Manages l) throws TorqueException
    {
        getManagess().add(l);
        l.setSupply((Supply) this);
    }

    /**
     * The criteria used to select the current contents of collManagess
     */
    private Criteria lastManagessCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getManagess(new Criteria())
     *
     * @throws TorqueException
     */
    public List getManagess() throws TorqueException
    {
        if (collManagess == null)
        {
            collManagess = getManagess(new Criteria(10));
        }
        return collManagess;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Supply has previously
     * been saved, it will retrieve related Managess from storage.
     * If this Supply is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getManagess(Criteria criteria) throws TorqueException
    {
        if (collManagess == null)
        {
            if (isNew())
            {
               collManagess = new ArrayList();
            }
            else
            {
                      criteria.add(ManagesPeer.SUPPLY_ID, getSupply_ID() );
                      collManagess = ManagesPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                      criteria.add(ManagesPeer.SUPPLY_ID, getSupply_ID());
                      if (!lastManagessCriteria.equals(criteria))
                {
                    collManagess = ManagesPeer.doSelect(criteria);
                }
            }
        }
        lastManagessCriteria = criteria;

        return collManagess;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getManagess(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getManagess(Connection con) throws TorqueException
    {
        if (collManagess == null)
        {
            collManagess = getManagess(new Criteria(10), con);
        }
        return collManagess;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Supply has previously
     * been saved, it will retrieve related Managess from storage.
     * If this Supply is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getManagess(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collManagess == null)
        {
            if (isNew())
            {
               collManagess = new ArrayList();
            }
            else
            {
                       criteria.add(ManagesPeer.SUPPLY_ID, getSupply_ID());
                       collManagess = ManagesPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                       criteria.add(ManagesPeer.SUPPLY_ID, getSupply_ID());
                       if (!lastManagessCriteria.equals(criteria))
                 {
                     collManagess = ManagesPeer.doSelect(criteria, con);
                 }
             }
         }
         lastManagessCriteria = criteria;

         return collManagess;
     }

                        
              
                    
                    
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Supply is new, it will return
     * an empty collection; or if this Supply has previously
     * been saved, it will retrieve related Managess from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Supply.
     */
    protected List getManagessJoinUser(Criteria criteria)
        throws TorqueException
    {
        if (collManagess == null)
        {
            if (isNew())
            {
               collManagess = new ArrayList();
            }
            else
            {
                            criteria.add(ManagesPeer.SUPPLY_ID, getSupply_ID());
                            collManagess = ManagesPeer.doSelectJoinUser(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                        criteria.add(ManagesPeer.SUPPLY_ID, getSupply_ID());
                        if (!lastManagessCriteria.equals(criteria))
            {
                collManagess = ManagesPeer.doSelectJoinUser(criteria);
            }
        }
        lastManagessCriteria = criteria;

        return collManagess;
    }
                  
                    
                              
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Supply is new, it will return
     * an empty collection; or if this Supply has previously
     * been saved, it will retrieve related Managess from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Supply.
     */
    protected List getManagessJoinSupply(Criteria criteria)
        throws TorqueException
    {
        if (collManagess == null)
        {
            if (isNew())
            {
               collManagess = new ArrayList();
            }
            else
            {
                            criteria.add(ManagesPeer.SUPPLY_ID, getSupply_ID());
                            collManagess = ManagesPeer.doSelectJoinSupply(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                        criteria.add(ManagesPeer.SUPPLY_ID, getSupply_ID());
                        if (!lastManagessCriteria.equals(criteria))
            {
                collManagess = ManagesPeer.doSelectJoinSupply(criteria);
            }
        }
        lastManagessCriteria = criteria;

        return collManagess;
    }
                            


          
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
              fieldNames.add("Supply_ID");
              fieldNames.add("Type");
              fieldNames.add("Name");
              fieldNames.add("Quantity");
              fieldNames.add("Source");
              fieldNames.add("Location");
              fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
          if (name.equals("Supply_ID"))
        {
                return new Integer(getSupply_ID());
            }
          if (name.equals("Type"))
        {
                return getType();
            }
          if (name.equals("Name"))
        {
                return getName();
            }
          if (name.equals("Quantity"))
        {
                return new Integer(getQuantity());
            }
          if (name.equals("Source"))
        {
                return getSource();
            }
          if (name.equals("Location"))
        {
                return getLocation();
            }
          return null;
    }
    
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
          if (name.equals(SupplyPeer.SUPPLY_ID))
        {
                return new Integer(getSupply_ID());
            }
          if (name.equals(SupplyPeer.TYPE))
        {
                return getType();
            }
          if (name.equals(SupplyPeer.NAME))
        {
                return getName();
            }
          if (name.equals(SupplyPeer.QUANTITY))
        {
                return new Integer(getQuantity());
            }
          if (name.equals(SupplyPeer.SOURCE))
        {
                return getSource();
            }
          if (name.equals(SupplyPeer.LOCATION))
        {
                return getLocation();
            }
          return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
        {
                return new Integer(getSupply_ID());
            }
              if (pos == 1)
        {
                return getType();
            }
              if (pos == 2)
        {
                return getName();
            }
              if (pos == 3)
        {
                return new Integer(getQuantity());
            }
              if (pos == 4)
        {
                return getSource();
            }
              if (pos == 5)
        {
                return getLocation();
            }
              return null;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
          save(SupplyPeer.getMapBuilder()
                .getDatabaseMap().getName());
      }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
       * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
       *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
          try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
      }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
          if (!alreadyInSave)
        {
            alreadyInSave = true;


  
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    SupplyPeer.doInsert((Supply) this, con);
                    setNew(false);
                }
                else
                {
                    SupplyPeer.doUpdate((Supply) this, con);
                }
            }

                                      
                
            if (collManagess != null)
            {
                for (int i = 0; i < collManagess.size(); i++)
                {
                    ((Manages) collManagess.get(i)).save(con);
                }
            }
                          alreadyInSave = false;
        }
      }


                          
      /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  supply_ID ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
            setSupply_ID(((NumberKey) key).intValue());
        }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
            setSupply_ID(Integer.parseInt(key));
        }

  
    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
          return SimpleKey.keyFor(getSupply_ID());
      }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
       * It then fills all the association collections and sets the
     * related objects to isNew=true.
       */
      public Supply copy() throws TorqueException
    {
        return copyInto(new Supply());
    }
  
    protected Supply copyInto(Supply copyObj) throws TorqueException
    {
          copyObj.setSupply_ID(supply_ID);
          copyObj.setType(type);
          copyObj.setName(name);
          copyObj.setQuantity(quantity);
          copyObj.setSource(source);
          copyObj.setLocation(location);
  
                    copyObj.setSupply_ID(0);
                                          
                                      
                
        List v = getManagess();
        for (int i = 0; i < v.size(); i++)
        {
            Manages obj = (Manages) v.get(i);
            copyObj.addManages(obj.copy());
        }
                    
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public SupplyPeer getPeer()
    {
        return peer;
    }

    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("Supply:\n");
        str.append("Supply_ID = ")
           .append(getSupply_ID())
           .append("\n");
        str.append("Type = ")
           .append(getType())
           .append("\n");
        str.append("Name = ")
           .append(getName())
           .append("\n");
        str.append("Quantity = ")
           .append(getQuantity())
           .append("\n");
        str.append("Source = ")
           .append(getSource())
           .append("\n");
        str.append("Location = ")
           .append(getLocation())
           .append("\n");
        return(str.toString());
    }
}
