package inventorysystem.dao;
import org.apache.torque.util.Criteria;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Feb 12 16:07:54 SGT 2010]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class ORFPeer
    extends inventorysystem.dao.BaseORFPeer
{
     public static boolean addORF(int userID,String ts){

        Criteria criteria = new Criteria();
        criteria.add(ORFPeer.STATUS, false);
        criteria.add(ORFPeer.USER_ID,userID);
        criteria.add(ORFPeer.ISSUE_DATE, ts);

        try{
            ORFPeer.doInsert(criteria);
            return true;
        }catch(Exception e){
            e.printStackTrace();
            return false;
        }
    }

     public static ORF retrieveORF(String ts, int userID){
        Criteria criteria = new Criteria();
        criteria.add(ORFPeer.USER_ID, userID);
        criteria.add(ORFPeer.ISSUE_DATE, ts);
        try{
            return (ORF)ORFPeer.doSelect(criteria).get(0);
        }catch(Exception e){
            e.printStackTrace();
            return null;
        }
    }
     
}
