package inventorysystem.dao;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Feb 12 16:07:54 SGT 2010]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */

import org.apache.torque.util.Criteria;

public class ORF_SupplyPeer
    extends inventorysystem.dao.BaseORF_SupplyPeer
{
        public static boolean addORFSupply(int orf_id,int user_id, String supplyType, String supplyName, String supplyQuantity, String supplyPrice){

        Criteria criteria = new Criteria();
        criteria.add(ORF_SupplyPeer.ORF_ID, orf_id);
        criteria.add(ORF_SupplyPeer.USER_ID, user_id);
        criteria.add(ORF_SupplyPeer.SUPPLY_NAME, supplyName);
        criteria.add(ORF_SupplyPeer.SUPPLY_TYPE, supplyType);
        criteria.add(ORF_SupplyPeer.QUANTITY, supplyQuantity);
        criteria.add(ORF_SupplyPeer.PRICE, supplyPrice);

        try{
            ORF_SupplyPeer.doInsert(criteria);
            return true;
        }catch(Exception e){
            e.printStackTrace();
            return false;
        }
    }
}
