
package inventorysystem.dao;


import java.util.StringTokenizer;
import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Feb 12 16:07:54 SGT 2010]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Supply
    extends inventorysystem.dao.BaseSupply
    implements Persistent
{
    public String returnSupplyName(){
        return(this.getName());
    }

    public int returnSupplyQuantity(){
        return(this.getQuantity());
    }

    public static String splitSupplyInfo(String supply){
        String[] st=supply.split("\r");
        StringTokenizer st2=new StringTokenizer(st[3]);
        String name="";
        st2.nextToken();
        st2.nextToken();
        while(st2.hasMoreTokens()){
            name += st2.nextToken()+" ";
        }
        return name;
    }


    public static boolean checkIfValidInput(String supplyName, String supplyType, String supplyQuantity){

        if(supplyName.equals(null)||supplyType.equals("novalue")||supplyQuantity.equals(null)){
            return false;
        }
        return true;
    }
}
