package inventorysystem.dao;

import java.util.ArrayList;
import java.util.List;
import org.apache.torque.util.Criteria;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Feb 12 16:07:54 SGT 2010]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class SupplyPeer
    extends inventorysystem.dao.BaseSupplyPeer
{
    public static List<Supply> retrieveAllSupplies(){
        Criteria criteria = new Criteria();
        try{
            return (List<Supply>)SupplyPeer.doSelect(criteria);
        }catch(Exception e){
            e.printStackTrace();
            return new ArrayList<Supply>();
        }
    }

    public static Supply retrieveSupply(String supplyname){
        Criteria criteria = new Criteria();
        criteria.add(SupplyPeer.NAME, supplyname);
        try{
            return (Supply)SupplyPeer.doSelect(criteria);
        }catch(Exception e){
            e.printStackTrace();
            return null;
        }
    }

     public static boolean addSupply(String supplyName,int newquantity){
         
        Criteria selectCriteria = new Criteria();
        selectCriteria.add(SupplyPeer.NAME, supplyName);

        Criteria criteria = new Criteria();
        criteria.add(SupplyPeer.QUANTITY, newquantity);

        try{
            SupplyPeer.doUpdate(selectCriteria, criteria);
            return true;
        }catch(Exception e){
            e.printStackTrace();
            return false;
        }
    }

     public static boolean deleteSupply(String supplyName){
        Criteria criteria = new Criteria();
        criteria.add(SupplyPeer.NAME, supplyName);
        try{
            UserPeer.doDelete(criteria);
            return true;
        }catch(Exception e){
            e.printStackTrace();
            return false;
        }

     }


}
