package inventorysystem.dao.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Sun Mar 21 15:11:40 CST 2010]
  *
  */
public class System_LogMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "inventorysystem.dao.map.System_LogMapBuilder";


    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("inventorysystemdb");

        dbMap.addTable("system_log");
        TableMap tMap = dbMap.getTable("system_log");

        tMap.setPrimaryKeyMethod(TableMap.NATIVE);


              tMap.addPrimaryKey("system_log.LOG_ID", new Integer(0));
                    tMap.addForeignKey(
                "system_log.USER_ID", new Integer(0) , "user" ,
                "user_id");
                    tMap.addColumn("system_log.ACTION", new String());
                    tMap.addColumn("system_log.LOCATION", new String());
                    tMap.addColumn("system_log.PREVIOUS_VALUE", new Integer(0));
                    tMap.addColumn("system_log.CURRENT_VALUE", new Integer(0));
                    tMap.addColumn("system_log.NOTES", new String());
                    tMap.addColumn("system_log.DATE", new String());
          }
}
